[project]
name = "frotzmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "zvm",
]

[tool.uv.sources]
zvm = { git = "https://github.com/sussman/zvm.git" }
